languages:
  PHP: true
exclude_paths:
  - "tests/*"
  - "example/*"
  - "bin/*"
  - "doc/*"
  - "config/*"
exclude_patterns:
- "src/Rad/Utils/Mime.php"
- "vendor/"
engines:
  sonar-php:
    enabled: true