<?php

/*
 * Copyright (C) 2017 Guillaume
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Rad\Http;

/**
 * Description of Bot
 *
 * @author Guillaume
 */
abstract class Bot {

    const CRAWLERS = array(
        '.*Java.*outbrain',
        '008\/',
        '^NING\/',
        'A6-Indexer',
        'Aboundex',
        'Accoona-AI-Agent',
        'acoon',
        'AddThis',
        'ADmantX',
        'AHC',
        'Airmail',
        'Anemone',
        'Apache-HttpClient\/',
        'Arachmo',
        'archive-com',
        'B-l-i-t-z-B-O-T',
        'Backlink-Ceck\.de',
        'baidu\.com',
        'BazQux',
        'bibnum\.bnf',
        'biglotron',
        'BingLocalSearch',
        'BingPreview',
        'binlar',
        'Bloglovin',
        'Blogtrottr',
        'boitho\.com-dc',
        'Browsershots',
        'BUbiNG',
        'Butterfly\/',
        'BuzzSumo',
        'CapsuleChecker',
        'CC Metadata Scaper',
        'Cerberian Drtrs',
        'changedetection',
        'Charlotte',
        'clips\.ua\.ac\.be',
        'CloudFlare-AlwaysOnline',
        'coccoc',
        'CommaFeed',
        'Commons-HttpClient',
        'convera',
        'cosmos',
        'corporatetwitnews',
        'Covario-IDS',
        'cron-job\.org',
        'Curious George',
        'curl',
        'CyberPatrol',
        'DataparkSearch',
        'dataprovider',
        'Daum(oa)?[ \/][0-9]',
        'developers\.google\.com\/\+\/web\/snippet\/',
        'Digg',
        'DomainAppender',
        'Dragonfly File Reader',
        'drupact',
        'EARTHCOM',
        'ec2linkfinder',
        'ECCP',
        'ElectricMonk',
        'EMail Exractor',
        'EmailWolf',
        'Embed PHP Library',
        'Embedly',
        'europarchive\.org',
        'EventMachine HttpClient',
        'ExactSearch',
        'ExaleadCloudview',
        'ezooms',
        'facebookexternalhit',
        'facebookplatform',
        'Feed Wrangler',
        'Feedbin',
        'FeedBurner',
        'Feedfetcher-Google',
        'Feedly',
        'Feedspot',
        'FeedValidator',
        'Fever',
        'findlink',
        'findthatfile',
        'Flamingo_SearchEngine',
        'FlipboardProxy',
        'fluffy',
        'Funnelback',
        'g00g1e\.net',
        'Genieo',
        'getprismatic\.com',
        'GigablastOpenSource',
        'Go-http-client',
        'Google favicon',
        'Google Keyword Suggestion',
        'Google Page Speed Insights',
        'Google Web Preview',
        'Google-HTTP-Java-Client',
        'Google-Site-Verification',
        'google_partner_monitoring',
        'GoogleProducer',
        'Grammarly',
        'grub-client',
        'heritrix',
        'Holmes',
        'htdig',
        'HTTPMon',
        'http-kit',
        'http_requester',
        'httpunit',
        'http_request2',
        'httrack',
        'HubPages.*crawlingpolicy',
        'HubSpot Marketing Grader',
        'ichiro',
        'IDG Twitter Links Resolver',
        'igdeSpyder',
        'InAGist',
        'infegy',
        'InfoWizards Reciprocal Link System PRO',
        'inpwrd\.com',
        'integromedb',
        'IODC',
        'IOI',
        'ips-agent',
        'iZSearch',
        '^Java\/',
        'Jigsaw',
        'Jobrapido',
        'kouio',
        'L\.webis',
        'Larbin',
        'libwww',
        'Link Valet',
        'linkCheck',
        'linkdex',
        'LinkExaminer',
        'LinkWalker',
        'Lipperhey',
        'link checker',
        'link validator',
        'LongURL API',
        'ltx71',
        'lwp-trivial',
        'lycos',
        'mabontland',
        'MagpieRSS',
        'Mediapartners-Google',
        'Mediapartners-Google',
        'MegaIndex\.ru',
        'MetaURI',
        'MergeFlow-PageReader',
        'Mnogosearch',
        'mogimogi',
        'Morning Paper',
        'Mrcgiguy',
        'MVAClient',
        'Netcraft Web Server Survey',
        'NetcraftSurveyAgent',
        'NetLyzer FastProbe',
        'netresearch',
        'Netvibes',
        'NewsBlur .*(Fetcher|Finder)',
        'NewsGator',
        'newsme',
        'NG-Search',
        'nineconnections\.com',
        'nominet\.org\.uk',
        'Notifixious',
        'nuhk',
        'nutch',
        'Nuzzel',
        'Nymesis',
        'oegp',
        'Omea Reader',
        'omgili',
        'Orbiter',
        'ow\.ly',
        'Go [\d\.]* package http',
        'page2rss',
        'PagePeeker',
        'panscient',
        'Peew',
        'PhantomJS\/',
        'phpcrawl',
        'phpservermon',
        'Pingdom\.com',
        'Pinterest',
        'Pizilla',
        'Ploetz \+ Zeller',
        'Plukkie',
        'PocketParser',
        'Pompos',
        'postano',
        'PostPost',
        'postrank',
        'proximic',
        'Pulsepoint XT3 web scraper',
        'Python-httplib2',
        'python-requests',
        'Python-urllib',
        'Qseero',
        'Qwantify',
        'Radian6',
        'RebelMouse',
        'RetrevoPageAnalyzer',
        'Riddler',
        'Robosourcer',
        'ROI Hunter',
        'Ruby',
        'SalesIntelligent',
        'SBIder',
        'scooter',
        'ScoutJet',
        'ScoutURLMonitor',
        'Scrapy',
        'Scrubby',
        'SearchSight',
        'semanticdiscovery',
        'SEOstats',
        'Server Density Service Monitoring.*',
        'servernfo\.com',
        'Seznam screenshot-generator',
        'ShopWiki',
        'SilverReader',
        'SimplePie',
        'Site24x7',
        'SiteBar',
        'siteexplorer\.info',
        'Siteimprove\.com',
        'SkypeUriPreview',
        'slider\.com',
        'slurp',
        'SMRF URL Expander',
        'Snappy',
        'SNK Siteshooter B0t',
        'sogou',
        'SortSite',
        'speedy',
        'Spinn3r',
        'Sqworm',
        'StackRambler',
        'Stratagems Kumo',
        'summify',
        'teoma',
        'theoldreader\.com',
        'TinEye',
        'Tiny Tiny RSS',
        'Traackr.com',
        'truwoGPS',
        'tweetedtimes\.com',
        'Twikle',
        'Typhoeus',
        'ubermetrics-technologies',
        'UdmSearch',
        'UnwindFetchor',
        'updated',
        'URLChecker',
        'urlresolver',
        'Vagabondo',
        'Validator\.nu\/LV',
        'via ggpht\.com GoogleImageProxy',
        'vkShare',
        'Vortex',
        'voyager\/',
        'VYU2',
        'W3C-checklink',
        'W3C-mobileOK',
        'W3C_CSS_Validator_JFouffa',
        'W3C_I18n-Checker',
        'W3C_Unicorn',
        'W3C_Validator',
        'web-capture\.net',
        'WebCapture',
        'WebCorp',
        'webcollage',
        'WebIndex',
        'WebFetch',
        'webmon ',
        'websitepulse[+ ]checker',
        'Websquash\.com',
        'WebThumbnail',
        'WeSEE:Search',
        'wf84',
        'wget',
        'WhatsApp',
        'WomlpeFactory',
        'WordPress\/',
        'wotbox',
        'www\.monitor\.us',
        'XaxisSemanticsClassifier',
        'Xenu Link Sleuth',
        'XML Sitemaps Generator',
        'Y!J-ASR',
        'yacy',
        'Yahoo Ad monitoring',
        'Yahoo Link Preview',
        'YahooSeeker',
        'yandex',
        'yanga',
        'yeti',
        'yoogliFetchAgent',
        'YottaaMonitor',
        'Zao',
        'zgrab',
        'ZyBorg',
        '[a-z0-9\-_]*((?<!cu)bot|crawler|archiver|transcoder|spider)',
    );

    private function __construct() {
        
    }

    /**
     * Test if current user is a bot
     * @return bool
     */
    public static function isBot() {
        if (preg_match('/' . implode('|', self::$crawlers) . '/i', trim($_SERVER['HTTP_USER_AGENT']))) {
            return true;
        } else {
            return false;
        }
    }

}
